upload_max_filesize=20M
post_max_size=20M
memory_limit=512M

; Speed up Laravel while still detecting local code changes.
opcache.enable=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.validate_timestamps=1
opcache.revalidate_freq=2

realpath_cache_size=4096K
realpath_cache_ttl=600
